1018 add stock picking removal date
qrtl/hls-custom pull request #102
Opened 2020-06-22 07:40 UTC by YogeshMahera-SerpentCS

- TASK #[1018](https://www.quartile.co/web#id=1018&action=771&model=project.task&view_type=form&menu_id=505)
- Added Test-Cases
- Improved Dependency issue

2020-06-22 14:18 UTC, yostashiro requested changes
@YogeshMahera-SerpentCS Please change the PR title to reflect what it is.

A reminder - going forward, please push your branch to our repos instead of to your fork so that it will be easier for other members to take over the PRs.

2020-06-22 14:18 UTC, yostashiro commented on stock_move_line_removal_date/models/stock_move_line.py
>              return utc_timestamp - relativedelta(hours=diff)
```suggestion
        diff = -(utc_timestamp - su_timestamp).seconds / 3600
        if su_timestamp > utc_timestamp:
            diff = (su_timestamp - utc_timestamp).seconds / 3600
        return utc_timestamp + relativedelta(hours=diff)
```

This would be slightly better for the Japan timezone.

2020-06-22 14:18 UTC, yostashiro commented on stock_move_line_removal_date/tests/test_stock_move_line.py
> +        which allows to convert date to datetime with Specific hours"""
```suggestion
        which converts removal date to a datetime according to superuser's timezone."""
```

2020-06-22 14:18 UTC, yostashiro commented on stock_move_line_removal_date/tests/test_stock_move_line.py
> +        # Move assignment
```suggestion
        # Confirm and assign move
        move1._action_confirm()
```
Remove unnecessary assertion.

2020-06-22 14:18 UTC, yostashiro commented on stock_move_line_removal_date/tests/test_stock_move_line.py
> +
```suggestion

        self.assertEqual(str(move_line_1.lot_id.removal_date), "2020-01-01 12:00:00")
```

2020-06-22 14:18 UTC, yostashiro commented on stock_move_line_removal_date/tests/test_stock_move_line.py
> +
```suggestion
```

2020-06-22 14:18 UTC, yostashiro commented on stock_move_line_removal_date/tests/test_stock_move_line.py
> +        # Comparing the Difference Hours Based on Japan timezone.
```suggestion
```

2020-06-23 04:20 UTC, YogeshMahera-SerpentCS commented
Closing this PR and Recreate PR from Main fork.

2020-06-23 04:20 UTC, closed without merging