[1216][ADD] sale_order_partner_shipping_propose
qrtl/hls-custom pull request #108
Opened 2020-09-30 07:17 UTC by TimLai125

#[1216](https://www.quartile.co/web#id=1216&model=project.task&view_type=form&menu_id=)

2020-10-02 06:05 UTC, yostashiro requested changes
@TimLai125 Could we change the name to "sale_order_value_proposal_by_partner_shipping", or is this too long?

2020-10-02 06:05 UTC, yostashiro commented on sale_order_partner_shipping_propose/__manifest__.py
> +    "license": "AGPL-3",
```suggestion
    "license": "LGPL-3",
```

2020-10-05 09:05 UTC, TimLai125 commented
> @TimLai125 Could we change the name to "sale_order_value_proposal_by_partner_shipping", or is this too long?

I think it is still acceptable. Let me update the name of the module

2020-10-05 12:25 UTC, yostashiro commented on sale_order_value_proposal_by_partner_shipping/models/res_partner.py
> +    warehouse_id = fields.Many2one("stock.warehouse", string="Warehouse")
Just came to think that this field should actually be a property field to make it more generic.  What do you think?

2020-10-06 07:48 UTC, yostashiro approved these changes
LGTM!

2020-10-07 01:36 UTC, merged