[1454][ADD] sale_line_note
qrtl/hls-custom pull request #121
Opened 2020-12-08 12:52 UTC by TimLai125

#[1454](https://www.quartile.co/web?debug=#id=1454&action=771&model=project.task&view_type=form&menu_id=505)

2020-12-09 04:28 UTC, yostashiro requested changes

2020-12-09 04:28 UTC, yostashiro commented on sale_line_note/views/sale_order_views.xml
> +            <xpath expr="//field[@name='order_line']//tree//field[@name='name']" position="after">
```suggestion
            <xpath expr="//field[@name='order_line']//tree//field[@name='price_tax']" position="after">
```
Customer requests that the field show at the end of the tree fields.

2020-12-09 04:28 UTC, yostashiro commented on sale_line_note/i18n/ja.po
> +msgstr "配送備考"
```suggestion
msgstr "配送ノート"
```
To be consistent with the field name in stock.move.

2020-12-11 05:53 UTC, yostashiro approved these changes
LGTM 👍

2020-12-11 06:42 UTC, merged

2020-12-11 06:43 UTC, TimLai125 commented
The TravisCI build fails for the pre-commit (the issue cannot be reproduced on the development, I will open another ticket to follow-up)