[1542][ADD] base_update_restrict_model
qrtl/hls-custom pull request #131
Opened 2021-01-29 10:09 UTC by TimLai125

[1542](https://www.quartile.co/web#id=1542&model=project.task&view_type=form&menu_id=)

2021-02-01 01:57 UTC, yostashiro requested changes
I suggest that we add add USAGE.rst (and maybe CONFIGURE.rst) to explain the settings/how to use it.

I understand that this module currently supports global (i.e. restrictions are either applied to all the selected models or otherwise per user), which itself is fine when we do not consider further granularity. When we start thinking about control per user per model, for example, the current design may make it a bit difficult to do so without compromising the UI/UX.

Ideally, the optimal design I think is to have another model ('model.access.restriction' or something) with a dedicated menu item, and contain the global and per-user restrictions in there, kind of similar to how record rules are structured.

It depends on how we envision the final state of this module, so please give me your idea.

2021-02-01 01:57 UTC, yostashiro commented on base_update_restrict_model/tests/test_base_update_restrict_model.py
> +        )
Looks like Travis is complaining that there is no email for the partner. Would it make it simpler to just directly create the user without creating a partner beforehand. I suppose that email should be automatically updated with the login that way.

2021-02-01 01:57 UTC, yostashiro commented on base_update_restrict_model/views/res_users_views.xml
> +                    icon="fa-eye"
These icons are a bit misleading (making an object read-only and restricting updates are different things).

I also prefer this style: https://github.com/odoo/odoo/blob/2fb44a86819fc6a7a6507d120c79639e2e9f8a6b/odoo/addons/base/views/res_users_views.xml#L166-L168

2021-02-03 06:45 UTC, yostashiro requested changes
Please follow up on the point of crediting Moises as we talked.

base_model_restrict_update sounds better to me as a module name, but it's not a strong suggestion.

Made miscellaneous comments on non-essential points.  I leave it up to you how you treat them.

I'd suggest that we always create a PR in the OCA first. We miss the opportunity to receive the community feedback at the initial stage, otherwise.

2021-02-03 06:45 UTC, yostashiro commented on base_update_restrict_model/models/res_users.py
>      restrict_update_permit = fields.Boolean(
```suggestion
    unrestrict_model_update = fields.Boolean(
```

2021-02-03 06:45 UTC, yostashiro commented on base_update_restrict_model/models/res_users.py
> +        "Update Permit", help="Set to true and the user can update restricted model."
```suggestion
        "Unrestrict Model Update", help="Set to true and the user can update restricted model."
```

2021-02-03 06:45 UTC, yostashiro commented on base_update_restrict_model/__manifest__.py
> +    "author": "Odoo Community Association (OCA), Quartile Limited",
Doesn't a company usually come before OCA? Not sure if that matters.

2021-02-03 06:45 UTC, yostashiro commented on base_update_restrict_model/models/ir_model.py
> +    update_restrict = fields.Boolean("Update Restrict Model")
```suggestion
    restrict_update = fields.Boolean(help="When selected, the model is restricted to read-only unless the user has the special permission.")
```

2021-02-04 15:15 UTC, yostashiro reviewed
@TimLai125 Please accredit Moises.

2021-02-04 15:15 UTC, yostashiro commented on base_model_restrict_update/views/res_users_views.xml
> +                <button name="toggle_unrestrict_model_update" type="object" class="oe_stat_button" icon="fa-eye">
I think `fa-pencil` may better represent what it is.

2021-02-05 04:06 UTC, yostashiro approved these changes
LGTM 👍

2021-02-05 07:07 UTC, TimLai125 commented
taken over by https://github.com/qrtl/hls-oca/pull/1

2021-02-05 07:07 UTC, closed without merging