[12.0] stock_move_sale_invoice_partner: add tests
qrtl/hls-custom pull request #201
Opened 2023-01-10 08:36 UTC by AungKoKoLin1997

2023-01-10 13:05 UTC, yostashiro approved these changes
Non-blocking comments out of preferences.

2023-01-10 13:05 UTC, yostashiro commented on stock_move_sale_invoice_partner/tests/test_stock_move_sale_invoice_partner.py
> +        self.picking_type = self.PickingType.search(
```suggestion
        self.picking_type = self.env["stock.picking.type"].search(
```

2023-01-10 13:05 UTC, yostashiro commented on stock_move_sale_invoice_partner/tests/test_stock_move_sale_invoice_partner.py
> +        self.PickingType = self.env["stock.picking.type"]
```suggestion
```

2023-01-10 13:05 UTC, yostashiro commented on stock_move_sale_invoice_partner/tests/test_stock_move_sale_invoice_partner.py
> +        invoice = order.mapped("invoice_ids")
```suggestion
        invoice = order.invoice_ids
```

2023-01-10 13:05 UTC, yostashiro commented on stock_move_sale_invoice_partner/tests/test_stock_move_sale_invoice_partner.py
> +        self.assertEqual(self.invoice_partner1, move.invoice_partner_id)
```suggestion
        self.assertEqual(move.invoice_partner_id, self.invoice_partner1)
```

2023-06-23 07:30 UTC, kanda999 requested changes
I think it's a test you made a long ago, so if there's anything to fix please fix it.

2023-06-23 07:30 UTC, kanda999 commented on stock_move_sale_invoice_partner/tests/test_stock_move_sale_invoice_partner.py
> +        self.Picking = self.env["stock.picking"]
we don't need StockMove or Picking as well as PickingType.

2023-06-23 07:30 UTC, kanda999 commented on stock_move_sale_invoice_partner/tests/test_stock_move_sale_invoice_partner.py
> +        )
What is this used for?

2023-11-26 12:03 UTC, closed without merging