[12.0][4319][ADD] sale_order_line_price_unit_pricelist
qrtl/hls-custom pull request #216
Opened 2024-02-21 05:35 UTC by AungKoKoLin1997

[4319](https://www.quartile.co/web#id=4319&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2024-04-13 03:52 UTC, yostashiro requested changes

2024-04-13 03:52 UTC, yostashiro commented on sale_order_line_price_unit_pricelist/models/sale_order.py
> +    @api.onchange(
```suggestion
    @api.depends(
```

2024-04-13 03:52 UTC, yostashiro commented on sale_order_line_price_unit_pricelist/__manifest__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
```suggestion
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
```
Please do the same for the rest of the relevant files.

2024-04-13 03:52 UTC, yostashiro commented on sale_order_line_price_unit_pricelist/models/sale_order_line.py
> +    @api.depends("product_id.item_ids", "order_id.pricelist_id")
```suggestion
    @api.depends(
        "product_id",
        "product_uom",
        "product_uom_qty",
        "order_id.partner_id",
        "order_id.date_order",
        "order_id.pricelist_id",
        "product_id.item_ids",
    )
```

2024-04-13 03:52 UTC, yostashiro commented on sale_order_line_price_unit_pricelist/models/sale_order_line.py
> +                )
The first line is avoid unnecessary computation.

```suggestion
        lines = self.fitered(lamba x: x.state != "cancel" and x.qty_invoiced == 0.0)
        for rec in lines:
            order = rec.order_id
            if not rec.product_uom or not rec.product_id or not order.pricelist_id or not order.partner_id:
                rec.price_unit_pricelist = 0.0
                continue
            product = rec.product_id.with_context(
                lang=order.partner_id.lang,
                partner=order.partner_id,
                quantity=rec.product_uom_qty,
                date=order.date_order,
                pricelist=order.pricelist_id.id,
                uom=rec.product_uom.id,
            )
            rec.price_unit_pricelist = self.env[
                "account.tax"
            ]._fix_tax_included_price_company(
                rec._get_display_price(product),
                product.taxes_id,
                rec.tax_id,
                rec.company_id,
            )
```

I suppose we don't need to assign the `fiscal_postion` context to the product.  Please confirm this point.

2024-04-15 10:26 UTC, yostashiro requested changes
Tested in the dev server, upon copying hlstest5.  It took approx. 4 mins and 20 secs to install.

2024-04-15 10:26 UTC, yostashiro commented on sale_order_line_price_unit_pricelist/models/sale_order.py
> +    is_price_matched = fields.Boolean(compute="_compute_is_price_matched", store=True)
We should reverse the objective of the field.

```suggestion
    has_price_discrepancy = fields.Boolean(compute="_compute_has_price_discrepancy", store=True)
```

2024-04-15 10:26 UTC, yostashiro commented on sale_order_line_price_unit_pricelist/models/sale_order.py
> +            )
```suggestion
    def _compute_has_price_discrepancy(self):
        for order in self:
            for line in order.order_line:
                if line.product_id.type == "service":
                    continue
                if line.price_unit != line.price_unit_pricelist:
                    order.has_price_discrepancy = True
                    break
```

2024-04-15 10:26 UTC, yostashiro commented on sale_order_line_price_unit_pricelist/views/sale_order_views.xml
> +                <filter string="Pricelist Changed" name="pricelist_changed" domain="[('is_price_matched','=',True)]"/>
```suggestion
                <filter string="Has Price Discrepancy" name="has_price_discrepancy" domain="[('has_price_discrepancy','=',True)]"/>
```

2024-04-16 08:13 UTC, yostashiro approved these changes
Code review.

@kanda999 Please add the translation.

2024-04-19 09:16 UTC, kanda999 approved these changes
Functioanl review

2024-04-19 09:18 UTC, merged