[12.0][4230][ADD] stock_picking_delivery_slip_required
qrtl/hls-custom pull request #217
Opened 2024-02-27 06:40 UTC by AungKoKoLin1997

[4230](https://www.quartile.co/web#id=4320&cids=3&model=project.task&view_type=form)

2024-03-18 08:45 UTC, kanda999 requested changes

2024-03-18 08:45 UTC, kanda999 commented on stock_picking_delivery_slip_required/models/stock_picking.py
> +    is_delivery_slip_required = fields.Boolean(
Can you use `get_default` and update it so that it does not affect past transaction data?

2024-03-21 01:19 UTC, kanda999 commented on stock_picking_delivery_slip_required/models/res_partner.py
> +    is_delivery_slip_required = fields.Boolean(default=True)
Any reason to set this to default=True? I thought false was fine.

2024-03-22 03:07 UTC, yostashiro commented on stock_picking_delivery_slip_required/models/stock_picking.py
> +        return res
To reduce writes.
```suggestion
        partner_id = vals.get("partner_id")
        if partner_id:
            partner = self.env["res.partner"].browse(partner_id)
            vals.update({"is_delivery_slip_required": partner.is_delivery_slip_required})
        return super(StockPicking, self).write(vals)
```

2024-03-22 04:56 UTC, yostashiro approved these changes
Code review.

2024-04-17 03:14 UTC, kanda999 approved these changes
Functinal review

2024-04-17 03:21 UTC, merged