[4804][IMP] sale_order_pricelist_commitment_date
qrtl/hls-custom pull request #228
Opened 2024-09-04 02:12 UTC by AungKoKoLin1997

[4804](https://www.quartile.co/web#id=4804&menu_id=517&cids=3&model=project.task&view_type=form)

2024-12-16 09:43 UTC, yostashiro reviewed
IMO, it would be better to just update `sale_order_pricelist_commitment_date` instead of having changes on the same method in two separate modules.

* Add `sale_order_secondary_unit_price` as a dependency of `sale_order_pricelist_commitment_date`
* Adjust `onchange_commitment_date()` accordingly
* No changes on `sale_order_secondary_unit_price`

2025-02-17 07:47 UTC, yostashiro commented on sale_order_secondary_unit_price/__manifest__.py
> +    ],
Avoid making unnecessary changes.

2025-02-17 07:47 UTC, yostashiro commented on sale_order_pricelist_commitment_date/models/sale_order.py
> +                    commitment_date=self.commitment_date,
```suggestion
                    date=self.commitment_date,
                    pricelist=self.pricelist_id.id,
                    uom=line.product_uom.id,
                    fiscal_position=self.env.context.get("fiscal_position"),
```

How about making it like this, and removing the adjustment on `_compute_price_rule()`?

2025-02-17 08:43 UTC, yostashiro requested changes
Sorry, removing the adjustments on `_compute_price_rule()` was a mistake -- it would break the price recalculation behavior when product, quantity, or UoM is changed.

2025-02-17 08:43 UTC, yostashiro commented on sale_order_pricelist_commitment_date/models/sale_order.py
> +                    fiscal_position=self.env.context.get("fiscal_position"),
```suggestion
                    date=self.date_order,
                    pricelist=self.pricelist_id.id,
                    uom=line.product_uom.id,
                    fiscal_position=self.env.context.get("fiscal_position"),
                    commitment_date=self.commitment_date,
```

2025-02-17 08:43 UTC, yostashiro commented on sale_order_pricelist_commitment_date/models/product_pricelist.py
> -        )
Please revive this.

2025-02-17 10:17 UTC, yostashiro approved these changes
Code review.

2025-02-25 08:27 UTC, AungKoKoLin1997 commented
@kanda999 @nobuQuartile Please review when you are available.

2025-02-27 09:18 UTC, nobuQuartile approved these changes
Functional test
LGTM

2025-03-17 04:11 UTC, nobuQuartile commented on sale_order_pricelist_commitment_date/models/sale_order.py
> +                line.secondary_uom_price = line.price_unit * factor
@AungKoKoLin1997 
Is the behavior of recalculating the Secondary Unit Price appropriate?
I find it strange that the value changes just by modifying the commitment_date.
How do you think?

2025-03-17 04:42 UTC, AungKoKoLin1997 commented on sale_order_pricelist_commitment_date/models/sale_order.py
> +                line.secondary_uom_price = line.price_unit * factor
Yes. Secondary Unit Price should be updated depends on price unit by using factor.

2025-04-03 04:19 UTC, AungKoKoLin1997 commented on sale_order_pricelist_commitment_date/models/sale_order.py
> +                line.secondary_uom_price = line.price_unit * factor
@nobuQuartile Do you understand the design?

2025-04-03 05:25 UTC, nobuQuartile commented on sale_order_pricelist_commitment_date/models/sale_order.py
> +                line.secondary_uom_price = line.price_unit * factor
I understand that the Secondary Unit Price needs to be recalculated because the pricelist_id is being updated. This pull request is currently waiting for customer confirmation, and I plan to bring it up as a topic in the next meeting

2025-06-30 02:20 UTC, kanda999 approved these changes
LGTM

2025-06-30 02:20 UTC, merged