[12.0][T968][ADD]- Added Sale Order Pricelist commitment date module
qrtl/hls-custom pull request #97
Opened 2020-05-07 15:03 UTC by YogeshMahera-SerpentCS

- Task #[968](https://www.quartile.co/web#id=968&action=771&model=project.task&view_type=form&menu_id=505)
 - Added `C901` in flake 8 file for ignore this warning
`sale_order_pricelist_commitment_date/models/product_pricelist.py:14:5: C901 'Pricelist._compute_price_rule' is too complex (33)`

2020-05-08 06:33 UTC, TimLai125 commented on sale_order_pricelist_commitment_date/models/product_pricelist.py
> +    def _compute_price_rule(self, products_qty_partner, date=False, uom_id=False):
```
@api.multi
def _compute_price_rule(self, products_qty_partner, date=False, uom_id=False):
    commitment_date = self._context.get("commitment_date") or False
    commitment_date = commitment_date or self._context.get("date") or fields.Date.today()
    super(Pricelist, self)._compute_price_rule(products_qty_partner, date=commitment_date, uom_id=uom_id)
```

2020-05-12 04:14 UTC, yostashiro commented
@YogeshMahera-SerpentCS I just checked the behavior myself. Maybe the approach we should take is to pass commitment_date to the context for all the line fields that triggers price updates (i.e. `product_id`, `product_uom_qty`, `product_uom`, `secondary_uom_qty`, `secondary_uom_id`).

Besides above, if we trigger price update when commitment_date is changed, we should cover all the possible patterns, I suppose.  What do you think?

2020-05-12 07:37 UTC, YogeshMahera-SerpentCS commented
Hi, @yostashiro I have amended changes for product_uom_qty,product_uom for form, and tree view both, Also amended changes while commitment_date change the already created order line will get the updated commitment_date unit price.

for `secondary_uom_qty,secondary_uom_id` I did check the when I am going to change on this field it's not going to change on-call this method `compute_price_rule`

So even If I pass the context on this field this method does not have any change in unit price. Let me know if I miss something else.

2020-05-12 09:23 UTC, YogeshMahera-SerpentCS commented
Hi @yostashiro Can you please check I have passed the context to `secondary_uom_id`

2020-05-12 10:02 UTC, yostashiro commented on sale_order_pricelist_commitment_date/__manifest__.py
> +    "application": False,
```suggestion
```

2020-05-12 10:02 UTC, yostashiro commented on sale_order_pricelist_commitment_date/tests/test_sale_pricelist.py
> +        )
Can't tell what this test is trying to prove...

2020-05-12 12:24 UTC, yostashiro requested changes
@YogeshMahera-SerpentCS Just a minor point. Please fix this and merge the PR.

2020-05-12 12:24 UTC, yostashiro commented on sale_order_pricelist_commitment_date/__manifest__.py
> +    "data": ["views/sale_order_view.xml"],
```suggestion
    "data": ["views/sale_order_views.xml"],
```

Following the OCA convention: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#file-naming

2020-05-12 13:51 UTC, YogeshMahera-SerpentCS commented
Hi, @yostashiro I have amended changes but it seems I don't have access to merge.

2020-05-12 13:54 UTC, yostashiro commented
@YogeshMahera-SerpentCS Try again please.

2020-05-12 14:09 UTC, merged